### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by robinpaulson** [jevonlongdell/nztides#15]

**Comment by robinpaulson** [comment]
Oops....
It's 4 months until the data expires.

**Comment by jevonlongdell** [comment]
Thanks for the prod, I've now got all the data I need to do it from Linz (just pushed). I should be able to get a new one out in the next month or so.

**Comment by robinpaulson** [comment]
Cool, glad to help.

**Comment by jevonlongdell** [comment]
data now included till end 2022

**Comment by robinpaulson** [comment]
I don't think f-droid will pick up the new release; from what I recall the release name and the tag both need to be something like:
v15
The descriptive phrase you've used might trip up the scanner.
