### ISSUE TITLE
Adding Maori names to the existing English names?

### ISSUE THREAD

**Issue by robinpaulson** [jevonlongdell/nztides#17]
Given the recent prominent debates over the language of location names, what do you think about adding Maori names to the existing English names?

e.g.
Tamaki Makaurau/Auckland
Ōtautahi/Christchurch

I don't mind putting the time in to find the Maori names and making sure the macrons are correct.

**Comment by jevonlongdell** [comment]
Whakaaro pai! But I think it will complicate things.  I'll follow linz on station names. They are making some progress in this regard, there are macrons in some of the station names now.
