### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by robinpaulson** [jevonlongdell/nztides#18]
It appears the data in the current release will expire at the end of this year.

**Comment by jevonlongdell** [comment]
I have update it v18, is in the packages folder. Data only lasts till mid next year but linz will send through more data well before that hopefully. Its currently in close beta on NZ tides. I'll push it to production hopefully in the next few dahys.

**Comment by jevonlongdell** [comment]
I meant "closed beta", this means that it goes out to a few users to  make sure nothing is broken ( I think you're one of them!)

However I was wrong, it hasn't yet been pushed to the beta channel, it is still "in review" with google, I'm not sure how long that will take but it's been two weeks so far. The new version is available [in the packages directory ](https://github.com/jevonlongdell/nztides/blob/master/packages/NZTides-v18.apk). I had a quick look to see if I could find how long this will take, but I'm a bit in the dark.

![Screen Shot 2022-10-20 at 8 11 41 AM](https://user-images.githubusercontent.com/978774/196783680-0a7e1541-72c0-4b6c-8530-f946f4604181.png)

**Comment by robinpaulson** [comment]
Ah, thanks. I didn't know there was a beta programme, I get it from fdroid anyway, I'll wait until it lands there

**Comment by robinpaulson** [comment]
It might need to be tagged as you did for v14 or the fdroid scanner won't recognise the new  release

**Comment by jevonlongdell** [comment]
This should be done now?

**Comment by robinpaulson** [comment]
Success! Closing

**Comment by robinpaulson** [comment]
Hi, I notice the data runs out in a couple of weeks. What's the situation for the new data set?

**Comment by jevonlongdell** [comment]
Life’s pretty busy at the moment it might not happen…
J.

From: robinpaulson ***@***.***>
Date: Saturday, 17 June 2023 at 8:43 PM
To: jevonlongdell/nztides ***@***.***>
Cc: Jevon Longdell ***@***.***>, Comment ***@***.***>
Subject: Re: [jevonlongdell/nztides] New release? (Issue #18)

Hi, I notice the data runs out in a couple of weeks. What's the situation for the new data set?

**Comment by jevonlongdell** [comment]
Hi NZ tides user.

I have updated NZ tides with the next year of tide data. So as soon as google has reviewed it, the update should reach you. This generally takes less than a week but can be longer.

If you don’t mind “unverified” apps then you can download the most recent version from

https://github.com/jevonlongdell/nztides/raw/master/packages/NZTides-v19.apk

Have fun on the water

Cheers
Jevon
