### ISSUE TITLE
LINZ copyright

### ISSUE THREAD

**Issue by robinpaulson** [jevonlongdell/nztides#2]
Hi, I see in your source code there is info about the tide data "probably being under Crown Copyright". Under NZ GOAL, most NZ government data is now CC of some variety, mostly CC-BY 3.0 NZ. See here for LINZ data:
http://www.linz.govt.nz/linz-copyright

Oh, great software by the way, I use it all the time around Onehunga.

Cheers,

Robin

**Comment by jevonlongdell** [comment]
I have tidied this up a bit, now says it's under crown copyright and points to the URL you mention.
Thanks for pointing this out.
Jevon
