### ISSUE TITLE
Wrong date and source code location in "strings.xml"

### ISSUE THREAD

**Issue by robinpaulson** [jevonlongdell/nztides#3]
This file notes data as being valid until "end of 2012"
https://github.com/jevonlongdell/nztides/blob/dbb92972587febcf84afb921f0388a6e145261e9/nztides_app_eclipse/res/values/strings.xml
also says code is hosted on code.google.com

**Comment by jevonlongdell** [comment]
You're looking at a old version of the source code here. I have renamed to make this clearer hopefully
