### ISSUE TITLE
add v7 to f-droid

### ISSUE THREAD

**Issue by robinpaulson** [jevonlongdell/nztides#4]
I'd ask for inclusion myself, but apparently there is a huge backlog, and I'll get tied in knots trying to do the git clone, git merge, git pull request thing....
Hints and more information here:
https://f-droid.org/forums/topic/read-this-before-posting/

Cheers

**Comment by fredcooke** [comment]
+1 sitting up at Tokerau Bay and cracked out my favourite/only tide app only to get a helpful message about updates with a null. While you're at it, update the source and website links as Google code goes offline in a day or two at the same time the tide data runs out. Chur chur, br0! :-)

**Comment by jevonlongdell** [comment]
You cand find the latest version on play store or  as a apk on github

https://github.com/jevonlongdell/nztides/blob/master/packages/NZTides-v7.apk

Not sure when I'll get a chance to look at droid.

**Comment by krt16s** [comment]
Should be fixed with https://gitlab.com/fdroid/fdroiddata/commit/7c87340a41ff08d538eedff502cbc9fb0138d986
