### ISSUE TITLE
Data for 2017 and onwards?

### ISSUE THREAD

**Issue by robinpaulson** [jevonlongdell/nztides#7]
According to my install, there is only data up to December 2016, which is ~7 weeks away. Could we get an upgrade for new data?

As an aside, I'm keen to include data for secondary ports (see #6) in the new release too, perhaps @jevonlongdell you could take a look at the comments to that issue and let me know what you think?

Cheers,

Robin

**Comment by jevonlongdell** [comment]
Thanks for the nudge, I have written to my contact at LINZ to ask for more data. (The stuff off the website is a bit of a pain these days because they correct for daylight savings time which makes the data ambiguos at the end of daylight savings).
