### ISSUE TITLE
Make port easier to select

### ISSUE THREAD

**Issue by robinpaulson** [jevonlongdell/nztides#8]
At the moment, selecting the correct port can be tricky for the following reasons, particularly if you frequently move around and require information at more than one port. We may add data for a lot more ports (see #6), making the problem worse:
1. the list is long
2. there are duplicate names in New Zealand (Waitangi in Chathams and Northland, French Bay in Auckland and elsewhere)
3. it is organised alphabetically, which makes it clumsy if you want to know the tides at the nearest port (say you are at a location which is not listed and want the best guess by referring to the nearest port for which data exist) but are not sure which that is.

The objective of this issue is to list and choose the preferred method(s) for selecting/listing ports. These are some ideas, please add more as you see fit. Please also critique as you go.
1. List the ports in one list, from North to South rather than alphabetically
2. Add the latitude and longitude in the port names, e.g. "Auckland, -36.8416, 174.7657"
3. Add the province to each port name, e.g. "Waitangi, Northland" (or "Northland, Waitangi")
4. Add an option in the "settings" dialogue to only show either north or south island data
5. Add an option in the "settings" dialogue to only show one province at a time.
6. Create some way of interfacing with an internal/external map provider. This could be a plugin/list of favourites for OSMAnd, using webview to plot the ports on a map from OSM/LINZ within NZ Tides.
7. your suggestion here

Complexity:
1., 2. and 3. are all relatively simple.
4. and 5. require a little more coding but may require combining with 1., 2., or 3
6. requires more coding and possibly requires the user to have another application installed (OSMAnd).

Usefulness:
1., 2., and 3. will mostly solve the problem
4. alone will not improve things dramatically
5. will solve part of the problem, but still requires some of 1., 2., or 3.
6. will assist with spatial recognition of locations (rather than processing somewhat abstract names/latitude and longitude) and is thus desirable for a lot of people

**Comment by jevonlongdell** [comment]
Another thing I thought of doing was ordering ports by distance from current location, along with something like "10km NW of here". The only potential problem is that if someone chooses something from the wrong coast the results will be a bit meaningless.

**Comment by robinpaulson** [comment]
Yes, that would be very useful. We shouldn't assume user has GPS though, so we'd need a manual method too. I agree it could also be a problem though, particularly around the Auckland isthmus, Warkworth, Kerikeri and Kaitaia where E coast to W coast distance is small.

**Comment by robinpaulson** [comment]
An addendum to option 6:
LINZ provides CC-licensed nautical charts in png format (see https://data.linz.govt.nz), these would make a useful and stable background for port selection, rather than OSM data which is liable to change and which generally focusses on structures, concepts, etc. on land rather than the sea.

**Comment by robinpaulson** [comment]
I realise this complicates what is purposefully a simple app. I'll close it and do something meaningful with my time instead.

**Comment by jevonlongdell** [comment]
I do appreciate you input!
